import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App";
import { ApiProvider } from "@reduxjs/toolkit/query/react";
import apiSlice from "./features/api/apiSlice";
import { Provider } from "react-redux";
import store from "./redux/store";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
createRoot(document.getElementById("root")).render(_jsx(StrictMode, { children: _jsx(ApiProvider, { api: apiSlice, children: _jsx(Provider, { store: store, children: _jsx(Router, { children: _jsx(Routes, { children: _jsx(Route, { path: "/*", element: _jsx(App, {}) }) }) }) }) }) }));
